package mvc.controllerview;

import entity.Log;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mvc.model.dao.LogDAO;
import myutils.Notificacao;

public class FormBuscarLog extends javax.swing.JFrame 
{
    private Notificacao notificacao = new Notificacao();
    
    public FormBuscarLog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLocQuartoNumero = new javax.swing.JLabel();
        tfLocQuartoNumero = new javax.swing.JTextField();
        btLocQuartoNumero = new javax.swing.JButton();
        btBuscarTodosQuartos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLogs = new javax.swing.JTable();
        btSair = new javax.swing.JButton();
        lbLogCodigo = new javax.swing.JLabel();
        tfCodigoLog = new javax.swing.JTextField();
        btBuscarLog = new javax.swing.JButton();
        btBuscarTodosLogs = new javax.swing.JButton();

        lbLocQuartoNumero.setText("Localizar Quarto por número:");

        btLocQuartoNumero.setText("...");
        btLocQuartoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLocQuartoNumeroActionPerformed(evt);
            }
        });

        btBuscarTodosQuartos.setText("BuscarTodos");
        btBuscarTodosQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarTodosQuartosActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableLogs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Usuário", "Descrição", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableLogs);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Close.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        lbLogCodigo.setText("Código:");

        btBuscarLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Search_1.png"))); // NOI18N
        btBuscarLog.setText("...");
        btBuscarLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarLogActionPerformed(evt);
            }
        });

        btBuscarTodosLogs.setText("BuscarTodos");
        btBuscarTodosLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarTodosLogsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btSair))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbLogCodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfCodigoLog, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBuscarLog, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(btBuscarTodosLogs)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogCodigo)
                    .addComponent(tfCodigoLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarLog, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarTodosLogs))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 809, 421);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLocQuartoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLocQuartoNumeroActionPerformed

    }//GEN-LAST:event_btLocQuartoNumeroActionPerformed

    private void btBuscarTodosQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarTodosQuartosActionPerformed

    }//GEN-LAST:event_btBuscarTodosQuartosActionPerformed

    private void btBuscarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarLogActionPerformed
        limparTabela();
        String codigo = tfCodigoLog.getText();
        tfCodigoLog.setText("");

        DefaultTableModel modelo = (DefaultTableModel)jTableLogs.getModel();
        
        try {
            LogDAO logDAO = new LogDAO();
            Log log = (Log) logDAO.buscar(codigo);

            if (log != null) {
                modelo.addRow(log.getDadosEmVetor());
            } else {
                notificacao.exibir("Nenhum Quarto Encontrado.", Notificacao.ERRO);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR", ""+ex, ERROR);
        }
    }//GEN-LAST:event_btBuscarLogActionPerformed

    private void btBuscarTodosLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarTodosLogsActionPerformed
        limparTabela();
        tfCodigoLog.setText("");

        DefaultTableModel modelo = (DefaultTableModel)jTableLogs.getModel();
        
        try {
            LogDAO logDAO = new LogDAO();
            ArrayList<Log> listaLog = (ArrayList<Log>) logDAO.buscarTodos();

            if (!listaLog.isEmpty()) {
                for (Log logDaLista : listaLog) {
                    modelo.addRow(logDaLista.getDadosEmVetor());
                }
            } else {
                notificacao.exibir("Nenhum Quarto Encontrado.", Notificacao.ERRO);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btBuscarTodosLogsActionPerformed

    private void limparTabela()
    {
        DefaultTableModel modelo = (DefaultTableModel)jTableLogs.getModel();
        for (int i = jTableLogs.getRowCount() - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarLog;
    private javax.swing.JButton btBuscarTodosLogs;
    private javax.swing.JButton btBuscarTodosQuartos;
    private javax.swing.JButton btLocQuartoNumero;
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLogs;
    private javax.swing.JLabel lbLocQuartoNumero;
    private javax.swing.JLabel lbLogCodigo;
    private javax.swing.JTextField tfCodigoLog;
    private javax.swing.JTextField tfLocQuartoNumero;
    // End of variables declaration//GEN-END:variables
}
