package mvc.controllerview;

public class FormPrincipal extends AbstractForm {

    public FormPrincipal() {
        initComponents();
        setExtendedState(FormPrincipal.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBarPrincipal = new javax.swing.JToolBar();
        btClientes = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btHospedagem = new javax.swing.JButton();
        btQuartos = new javax.swing.JButton();
        btMobilia = new javax.swing.JButton();
        btCalculadora = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btSair = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();
        jPanelHospedagem = new javax.swing.JPanel();
        btHospedar = new javax.swing.JButton();
        btFecharHospedagem = new javax.swing.JButton();
        btCancelarHosp = new javax.swing.JButton();
        btEditarHops = new javax.swing.JButton();
        btSair1 = new javax.swing.JButton();
        lbBuscarHospedagem = new javax.swing.JLabel();
        tfBuscarHospedagemCodigo = new javax.swing.JTextField();
        btListarPorCodigo = new javax.swing.JButton();
        btListarTodas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btExcluirReserva = new javax.swing.JButton();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemQuarto = new javax.swing.JMenuItem();
        jMenuItemTipoQuarto = new javax.swing.JMenuItem();
        jMenuItemMobilia = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItemConsultaClientes = new javax.swing.JMenuItem();
        jMenuItemConsultaQuarto = new javax.swing.JMenuItem();
        jMenuSuporte = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Rooms | Principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBarPrincipal.setRollover(true);

        btClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/User group.png"))); // NOI18N
        btClientes.setText("Clientes");
        btClientes.setFocusable(false);
        btClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });
        jToolBarPrincipal.add(btClientes);
        jToolBarPrincipal.add(jSeparator3);

        btHospedagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Home.png"))); // NOI18N
        btHospedagem.setText("Hospadagem");
        btHospedagem.setFocusable(false);
        btHospedagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btHospedagem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btHospedagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHospedagemActionPerformed(evt);
            }
        });
        jToolBarPrincipal.add(btHospedagem);

        btQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Green tag.png"))); // NOI18N
        btQuartos.setText("Quartos");
        btQuartos.setFocusable(false);
        btQuartos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btQuartos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuartosActionPerformed(evt);
            }
        });
        jToolBarPrincipal.add(btQuartos);

        btMobilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Target.png"))); // NOI18N
        btMobilia.setText("Mobilia");
        btMobilia.setFocusable(false);
        btMobilia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMobilia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btMobilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMobiliaActionPerformed(evt);
            }
        });
        jToolBarPrincipal.add(btMobilia);

        btCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Calculator.png"))); // NOI18N
        btCalculadora.setText("Calculadora");
        btCalculadora.setFocusable(false);
        btCalculadora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCalculadora.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalculadoraActionPerformed(evt);
            }
        });
        jToolBarPrincipal.add(btCalculadora);
        jToolBarPrincipal.add(jSeparator2);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Exit.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setFocusable(false);
        btSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jToolBarPrincipal.add(btSair);

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/logoHotelRooms.png"))); // NOI18N

        jPanelHospedagem.setBorder(javax.swing.BorderFactory.createTitledBorder("Hospedagem"));
        jPanelHospedagem.setPreferredSize(new java.awt.Dimension(830, 490));

        btHospedar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/New.png"))); // NOI18N
        btHospedar.setText("Hospedar");
        btHospedar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHospedarActionPerformed(evt);
            }
        });

        btFecharHospedagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Dollar.png"))); // NOI18N
        btFecharHospedagem.setText("Fechar Hospedagem");
        btFecharHospedagem.setEnabled(false);
        btFecharHospedagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharHospedagemActionPerformed(evt);
            }
        });

        btCancelarHosp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/No-entry.png"))); // NOI18N
        btCancelarHosp.setText("Cancelar");

        btEditarHops.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Modify.png"))); // NOI18N
        btEditarHops.setText("Editar");
        btEditarHops.setEnabled(false);

        btSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Close.png"))); // NOI18N
        btSair1.setText("Sair");
        btSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSair1ActionPerformed(evt);
            }
        });

        lbBuscarHospedagem.setText("Código:");

        btListarPorCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Search_1.png"))); // NOI18N
        btListarPorCodigo.setText("Listar");

        btListarTodas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Search.png"))); // NOI18N
        btListarTodas.setText("Listar Todas");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Blue tag.png"))); // NOI18N
        jButton1.setText("Listar Hospedagens");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cliente", "Quarto", "Tipo Quarto", "Data Entrada", "Qtd Hopedes", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(4).setResizable(false);
        jTable1.getColumnModel().getColumn(5).setResizable(false);
        jTable1.getColumnModel().getColumn(6).setResizable(false);

        btExcluirReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Remove.png"))); // NOI18N
        btExcluirReserva.setText("Excluir");
        btExcluirReserva.setEnabled(false);

        javax.swing.GroupLayout jPanelHospedagemLayout = new javax.swing.GroupLayout(jPanelHospedagem);
        jPanelHospedagem.setLayout(jPanelHospedagemLayout);
        jPanelHospedagemLayout.setHorizontalGroup(
            jPanelHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHospedagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHospedagemLayout.createSequentialGroup()
                        .addComponent(btHospedar)
                        .addGap(18, 18, 18)
                        .addComponent(btFecharHospedagem)
                        .addGap(18, 18, 18)
                        .addComponent(btEditarHops)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExcluirReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCancelarHosp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSair1))
                    .addGroup(jPanelHospedagemLayout.createSequentialGroup()
                        .addComponent(lbBuscarHospedagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBuscarHospedagemCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btListarPorCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(btListarTodas)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 201, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanelHospedagemLayout.setVerticalGroup(
            jPanelHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHospedagemLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBuscarHospedagem)
                    .addComponent(tfBuscarHospedagemCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btListarPorCodigo)
                    .addComponent(btListarTodas)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btHospedar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btFecharHospedagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEditarHops, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSair1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelHospedagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btExcluirReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelarHosp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );

        jMenuCadastro.setText("Cadastro");

        jMenuItemCliente.setText("Clientes");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCliente);

        jMenuItemQuarto.setText("Quartos");
        jMenuItemQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuartoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemQuarto);

        jMenuItemTipoQuarto.setText("Tipo Quarto");
        jMenuItemTipoQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTipoQuartoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemTipoQuarto);

        jMenuItemMobilia.setText("Mobilia");
        jMenuItemMobilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMobiliaActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemMobilia);
        jMenuCadastro.add(jSeparator1);

        jMenuItemSair.setText("Sair");
        jMenuCadastro.add(jMenuItemSair);

        jMenuBarPrincipal.add(jMenuCadastro);

        jMenuConsultas.setText("Consultas");

        jMenuItemConsultaClientes.setText("Clientes");
        jMenuConsultas.add(jMenuItemConsultaClientes);

        jMenuItemConsultaQuarto.setText("Quartos");
        jMenuConsultas.add(jMenuItemConsultaQuarto);

        jMenuBarPrincipal.add(jMenuConsultas);

        jMenuSuporte.setText("Suporte");

        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuSuporte.add(jMenuItemSobre);

        jMenuBarPrincipal.add(jMenuSuporte);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1202, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHospedagem, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLogo))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBarPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 402, Short.MAX_VALUE)
                        .addComponent(lbLogo)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelHospedagem, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        FormCadastroCliente cadCli = new FormCadastroCliente();
        cadCli.setVisible(true);
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuartoActionPerformed
        FormCadastroQuarto cadQuarto = new FormCadastroQuarto();
        cadQuarto.setVisible(true);
    }//GEN-LAST:event_jMenuItemQuartoActionPerformed

    private void jMenuItemTipoQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTipoQuartoActionPerformed
        FormCadastroTipoQuarto cadTipoQuarto = new FormCadastroTipoQuarto();
        cadTipoQuarto.setVisible(true);
    }//GEN-LAST:event_jMenuItemTipoQuartoActionPerformed

    private void jMenuItemMobiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMobiliaActionPerformed
        FormCadastroMobilia cadMobilia = new FormCadastroMobilia();
        cadMobilia.setVisible(true);
    }//GEN-LAST:event_jMenuItemMobiliaActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        FormSobre fSobre = new FormSobre();
        fSobre.setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
        FormBuscarCliente fBuscarCliente = new FormBuscarCliente();
        fBuscarCliente.setVisible(true);
    }//GEN-LAST:event_btClientesActionPerformed

    private void btHospedagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHospedagemActionPerformed
        
    }//GEN-LAST:event_btHospedagemActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalculadoraActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btCalculadoraActionPerformed

    private void btQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuartosActionPerformed
        FormBuscarQuartos fBuscarQuartos = new FormBuscarQuartos();
        fBuscarQuartos.setVisible(true);
    }//GEN-LAST:event_btQuartosActionPerformed

    private void btMobiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMobiliaActionPerformed
        FormBuscarMobilia fBuscarMobilia = new FormBuscarMobilia();
        fBuscarMobilia.setVisible(true);
    }//GEN-LAST:event_btMobiliaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btHospedarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHospedarActionPerformed
        FormReserva fReserva = new FormReserva();
        fReserva.setVisible(true);
    }//GEN-LAST:event_btHospedarActionPerformed

    private void btSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSair1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSair1ActionPerformed

    private void btFecharHospedagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharHospedagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFecharHospedagemActionPerformed
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalculadora;
    private javax.swing.JButton btCancelarHosp;
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btEditarHops;
    private javax.swing.JButton btExcluirReserva;
    private javax.swing.JButton btFecharHospedagem;
    private javax.swing.JButton btHospedagem;
    private javax.swing.JButton btHospedar;
    private javax.swing.JButton btListarPorCodigo;
    private javax.swing.JButton btListarTodas;
    private javax.swing.JButton btMobilia;
    private javax.swing.JButton btQuartos;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSair1;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemConsultaClientes;
    private javax.swing.JMenuItem jMenuItemConsultaQuarto;
    private javax.swing.JMenuItem jMenuItemMobilia;
    private javax.swing.JMenuItem jMenuItemQuarto;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenuItem jMenuItemTipoQuarto;
    private javax.swing.JMenu jMenuSuporte;
    private javax.swing.JPanel jPanelHospedagem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBarPrincipal;
    private javax.swing.JLabel lbBuscarHospedagem;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JTextField tfBuscarHospedagemCodigo;
    // End of variables declaration//GEN-END:variables
}
