package mvc.controllerview;

import myutils.DateCustomizer;
import myutils.FormCustomizer;
import entity.Cliente;
import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mvc.model.dao.ClienteDAO;
import myutils.Notificacao;

public class FormCadastroCliente extends javax.swing.JFrame {

    public static Cliente cliente = null;
    private Notificacao notificacao = new Notificacao();
    
    public FormCadastroCliente() {
        initComponents();
 
        try {
            ClienteDAO clienteDAO = new ClienteDAO();
            tfCodigo.setText(String.valueOf(clienteDAO.getIndex()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERROR", ""+ex, ERROR);
        }
        
        /*Caso o Form esteja sendo aberto com intuito de 
        * realizar uma atualização, o objeto global
        * cliente foi preenchido diretamente por outro
        * Form.
        */
        if(cliente != null) {
            btAtualizar.setEnabled(true);
            btRemover.setEnabled(true);
            btCadastrar.setEnabled(false);         
            preencherFormCom(cliente);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDadosPessoais = new javax.swing.JPanel();
        tfCodigo = new javax.swing.JTextField();
        lbCodigo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lbCpf = new javax.swing.JLabel();
        tformatadoCpf = new javax.swing.JFormattedTextField();
        lbRg = new javax.swing.JLabel();
        tfRg = new javax.swing.JTextField();
        lbDataNasc = new javax.swing.JLabel();
        tformatadoDataNasc = new javax.swing.JFormattedTextField();
        btBuscarCpf = new javax.swing.JButton();
        lbModeloData = new javax.swing.JLabel();
        painelContato = new javax.swing.JPanel();
        tfTelResidencial = new javax.swing.JLabel();
        tformatadoTelCelular = new javax.swing.JFormattedTextField();
        lbCelular = new javax.swing.JLabel();
        lbTelComercial = new javax.swing.JLabel();
        tformatadoTelComercial = new javax.swing.JFormattedTextField();
        tformatadoTelResidencial = new javax.swing.JFormattedTextField();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        painelEndereco = new javax.swing.JPanel();
        lbRua = new javax.swing.JLabel();
        tfRua = new javax.swing.JTextField();
        lbNumero = new javax.swing.JLabel();
        tfNumeroEnd = new javax.swing.JTextField();
        lbCidade = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        comboEstado = new javax.swing.JComboBox();
        lbEstado = new javax.swing.JLabel();
        lbcomplemento = new javax.swing.JLabel();
        lbCep = new javax.swing.JLabel();
        tformatadoCep = new javax.swing.JFormattedTextField();
        tfComplemento = new javax.swing.JTextField();
        lbObservacao = new javax.swing.JLabel();
        jScrollPaneObs = new javax.swing.JScrollPane();
        taObs = new javax.swing.JTextArea();
        btCadastrar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        lbErro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hotel Rooms | Cadastro de Clientes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        painelDadosPessoais.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        tfCodigo.setEnabled(false);

        lbCodigo.setText("Código:");

        lbNome.setText("Nome: *");

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        lbCpf.setText("CPF: *");

        try {
            tformatadoCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbRg.setText("RG: *");

        lbDataNasc.setText("Data Nascimento: *");

        try {
            tformatadoDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btBuscarCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Search_1.png"))); // NOI18N
        btBuscarCpf.setText("Buscar");
        btBuscarCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarCpfActionPerformed(evt);
            }
        });

        lbModeloData.setText("dd/MM/aaaa");

        javax.swing.GroupLayout painelDadosPessoaisLayout = new javax.swing.GroupLayout(painelDadosPessoais);
        painelDadosPessoais.setLayout(painelDadosPessoaisLayout);
        painelDadosPessoaisLayout.setHorizontalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNome))
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCpf)
                                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(tformatadoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btBuscarCpf)))
                                .addGap(47, 47, 47)
                                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbRg))
                                .addGap(32, 32, 32)
                                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDataNasc)
                                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                        .addComponent(tformatadoDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbModeloData))))
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(lbCodigo)
                                .addGap(28, 28, 28)
                                .addComponent(lbNome)))
                        .addGap(0, 189, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelDadosPessoaisLayout.setVerticalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(lbNome))
                .addGap(12, 12, 12)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDataNasc)
                    .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCpf)
                        .addComponent(lbRg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tformatadoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tformatadoDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbModeloData)
                    .addComponent(btBuscarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        painelContato.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));

        tfTelResidencial.setText("Tel Residencial:");

        try {
            tformatadoTelCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tformatadoTelCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tformatadoTelCelularActionPerformed(evt);
            }
        });

        lbCelular.setText("Celular:");

        lbTelComercial.setText("Tel Comercial:");

        try {
            tformatadoTelComercial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tformatadoTelResidencial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbEmail.setText("E-mail:");

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelContatoLayout = new javax.swing.GroupLayout(painelContato);
        painelContato.setLayout(painelContatoLayout);
        painelContatoLayout.setHorizontalGroup(
            painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTelResidencial)
                    .addComponent(tformatadoTelResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tformatadoTelComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelComercial))
                .addGap(18, 18, 18)
                .addGroup(painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tformatadoTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCelular))
                .addGap(18, 18, 18)
                .addGroup(painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelContatoLayout.createSequentialGroup()
                        .addComponent(lbEmail)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfEmail))
                .addContainerGap())
        );
        painelContatoLayout.setVerticalGroup(
            painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelResidencial)
                    .addComponent(lbTelComercial)
                    .addComponent(lbCelular)
                    .addComponent(lbEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tformatadoTelResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tformatadoTelComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tformatadoTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        lbRua.setText("Rua: *");

        lbNumero.setText("Numero: *");

        lbCidade.setText("Cidade: *");

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC Acre", "AL Alagoas ", "AP Amapá ", "AM Amazonas ", "BA Bahia ", "CE Ceará ", "DF Distrito Federal ", "GO Goiás ", "ES Espírito Santo ", "MA Maranhão ", "MT Mato Grosso ", "MS Mato Grosso do Sul ", "MG Minas Gerais ", "PA Pará ", "PB Paraiba ", "PR Paraná ", "PE Pernambuco ", "PI Piauí ", "RJ Rio de Janeiro ", "RN Rio Grande do Norte ", "RS Rio Grande do Sul ", "RO Rondônia ", "RR Rorâima ", "SP São Paulo ", "SC Santa Catarina ", "SE Sergipe ", "TO Tocantins" }));

        lbEstado.setText("Estado: *");

        lbcomplemento.setText("Complemento:");

        lbCep.setText("CEP:");

        try {
            tformatadoCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout painelEnderecoLayout = new javax.swing.GroupLayout(painelEndereco);
        painelEndereco.setLayout(painelEnderecoLayout);
        painelEnderecoLayout.setHorizontalGroup(
            painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelEnderecoLayout.createSequentialGroup()
                        .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelEnderecoLayout.createSequentialGroup()
                                .addComponent(lbRua)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfRua))
                        .addGap(18, 18, 18)
                        .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNumero)
                            .addComponent(tfNumeroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbcomplemento)))
                    .addGroup(painelEnderecoLayout.createSequentialGroup()
                        .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelEnderecoLayout.createSequentialGroup()
                                .addComponent(lbCidade)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfCidade))
                        .addGap(18, 18, 18)
                        .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEstado))
                        .addGap(55, 55, 55)
                        .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCep)
                            .addComponent(tformatadoCep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        painelEnderecoLayout.setVerticalGroup(
            painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRua)
                    .addComponent(lbNumero)
                    .addComponent(lbcomplemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNumeroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCidade)
                    .addComponent(lbEstado)
                    .addComponent(lbCep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tformatadoCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lbObservacao.setText("Observação:");

        taObs.setColumns(20);
        taObs.setRows(5);
        jScrollPaneObs.setViewportView(taObs);

        btCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Add.png"))); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Refresh.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setEnabled(false);
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Close.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Exit.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24x24/Remove.png"))); // NOI18N
        btRemover.setText("Remover");
        btRemover.setEnabled(false);
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        lbErro.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneObs, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbErro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btRemover)
                        .addGap(18, 18, 18)
                        .addComponent(btCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSair))
                    .addComponent(painelContato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbObservacao, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelDadosPessoais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbErro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelDadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(painelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lbObservacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneObs, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(71, 71, 71))
        );

        setSize(new java.awt.Dimension(829, 727));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void tformatadoTelCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tformatadoTelCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tformatadoTelCelularActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        Cliente novoCliente = new Cliente();
        
        if(camposObrigatoriosPreenchidos()) {
            novoCliente.setNome(tfNome.getText());
            novoCliente.setCpf(tformatadoCpf.getText());
            novoCliente.setRg(tfRg.getText());
            try {
                novoCliente.setDataNascimento(DateCustomizer.StrToDate(tformatadoDataNasc.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(FormCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            novoCliente.setComplemento(tfComplemento.getText());
            novoCliente.setRua(tfRua.getText());
            novoCliente.setNumeroEnd(tfNumeroEnd.getText());
            novoCliente.setCidade(tfCidade.getText());
            novoCliente.setEstado((String)comboEstado.getSelectedItem());
            novoCliente.setCep(tformatadoCep.getText());
            novoCliente.setFoneCelular(tformatadoTelCelular.getText());
            novoCliente.setFoneResidencial(tformatadoTelResidencial.getText());
            novoCliente.setFoneComercial(tformatadoTelComercial.getText());
            novoCliente.setEmail(tfEmail.getText());
            novoCliente.setObservação(taObs.getText());
            
            try {
                ClienteDAO clienteDAO = new ClienteDAO();
                novoCliente.setCodigo(clienteDAO.getIndex());
                clienteDAO.inserir(novoCliente);
                notificacao.exibir("Cliente " + novoCliente.getNome() + " "
                        + "foi cadastrado com sucesso", Notificacao.SUCESSO);
                FormCustomizer.limparTodosCampos(painelDadosPessoais);
                FormCustomizer.limparTodosCampos(painelEndereco);
                FormCustomizer.limparTodosCampos(painelContato);
                taObs.setText("");
                tfNome.requestFocus();  
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "ERROR", ""+ex, ERROR);
            }   
        } else {
            notificacao.exibir("Os Campos com * são obrigatorios!", Notificacao.ERRO);
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        btCadastrar.setEnabled(true);
        FormCustomizer.limparTodosCampos(painelContato);
        FormCustomizer.limparTodosCampos(painelDadosPessoais);
        FormCustomizer.limparTodosCampos(painelEndereco);
        taObs.setText("");
    }//GEN-LAST:event_btCancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void btBuscarCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarCpfActionPerformed
        try {
            String cpfBusca = tformatadoCpf.getText();
            ClienteDAO clienteDAO = new ClienteDAO();
            Cliente clienteBusca = clienteDAO.buscarPorCpf(cpfBusca);
            if(clienteBusca != null) {
                btCadastrar.setEnabled(false);
                btAtualizar.setEnabled(true);
                btRemover.setEnabled(true);

                tfCodigo.setText(Integer.toString(clienteBusca.getCodigo()));
                tfNome.setText(clienteBusca.getNome());
                tfRg.setText(clienteBusca.getRg());
                tformatadoDataNasc.setText(DateCustomizer.DateToStr(
                            clienteBusca.getDataNascimento())
                        );
                tfRua.setText(clienteBusca.getRua());
                tfComplemento.setText(clienteBusca.getComplemento());
                tfNumeroEnd.setText(clienteBusca.getNumeroEnd());
                tfCidade.setText(clienteBusca.getCidade());
                comboEstado.setSelectedItem((String)clienteBusca.getEstado());
                tformatadoCep.setText(clienteBusca.getCep());
                tformatadoTelResidencial.setText(clienteBusca.getFoneResidencial());
                tformatadoTelCelular.setText(clienteBusca.getFoneCelular());
                tformatadoTelComercial.setText(clienteBusca.getFoneComercial());
                tfEmail.setText(clienteBusca.getEmail());
                taObs.setText(clienteBusca.getObservação());
            } else {  
              notificacao.exibir("Nenhum Cliente com o CPF: " + 
                                    tformatadoCpf.getText(), Notificacao.ERRO);
              btAtualizar.setEnabled(false);
              btRemover.setEnabled(false);
              btCadastrar.setEnabled(true);
            }
        } catch (Exception ex) {
              JOptionPane.showMessageDialog(null, "ERROR", ""+ex, ERROR);
        }
    }//GEN-LAST:event_btBuscarCpfActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        String codigo = tfCodigo.getText();
        try {
            ClienteDAO clienteDAO = new ClienteDAO();
            Cliente clienteParaAtualizar = clienteDAO.buscar(codigo);
            clienteParaAtualizar.setCidade(tfCidade.getText());
            clienteParaAtualizar.setCep(tformatadoCep.getText());
            clienteParaAtualizar.setComplemento(tfComplemento.getText());
            clienteParaAtualizar.setCpf(tformatadoCpf.getText());
            clienteParaAtualizar.setDataNascimento(
                    DateCustomizer.StrToDate(tformatadoDataNasc.getText())
                    );
            clienteParaAtualizar.setEmail(tfEmail.getText());
            clienteParaAtualizar.setEstado((String) comboEstado.getSelectedItem());
            clienteParaAtualizar.setFoneCelular(tformatadoTelCelular.getText());
            clienteParaAtualizar.setFoneComercial(tformatadoTelComercial.getText());
            clienteParaAtualizar.setFoneResidencial(tformatadoTelResidencial.getText());
            clienteParaAtualizar.setNome(tfNome.getText());
            clienteParaAtualizar.setNumeroEnd(tfNumeroEnd.getText());
            clienteParaAtualizar.setObservação(taObs.getText());
            clienteParaAtualizar.setRg(tfRg.getText());
            clienteParaAtualizar.setRua(tfRua.getText());
            clienteDAO.atualizar(codigo, clienteParaAtualizar);
            notificacao.exibir("Cliente " + clienteParaAtualizar.getNome() +
                    " atualizado com sucesso!", Notificacao.SUCESSO);
        } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "ERROR", ""+ex, ERROR);
        } finally {
            cliente = null;
        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        int codigo = Integer.parseInt(tfCodigo.getText());
        String nomeCliente = tfNome.getText();
        
        int i = JOptionPane.showConfirmDialog(null, "Confirma a exclusão do "
                                              + "cliente: " + tfNome.getText());
        
        if(i == 0) {
            try {
                 ClienteDAO clienteDAO = new ClienteDAO();
                 clienteDAO.remover(Integer.toString(codigo));
                 notificacao.exibir("Cliente " + nomeCliente + " "
                         + "foi removido com sucesso", Notificacao.SUCESSO);
                   
                FormCustomizer.limparTodosCampos(painelDadosPessoais);
                FormCustomizer.limparTodosCampos(painelContato);
                FormCustomizer.limparTodosCampos(painelEndereco);
            } catch (Exception ex) {
                 JOptionPane.showMessageDialog(null, "ERROR", ""+ex, ERROR);
            }
        } else {
            tfNome.requestFocus();
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        cliente = null;
    }//GEN-LAST:event_formWindowClosed

    public boolean camposObrigatoriosPreenchidos()
    {
        boolean retorno = true;
        
        if(tfNome.getText().equals("")) {
            tfNome.setBackground(Color.orange);
            retorno = false;
        } else {
            tfNome.setBackground(Color.WHITE);
        }
        
        if(tformatadoCpf.getText().equals("   .   .   -  ")) {
            tformatadoCpf.setBackground(Color.orange);
            retorno = false;
        } else {
            tformatadoCpf.setBackground(Color.WHITE);
        }
        
        if(tfRg.getText().equals("")) {
            tfRg.setBackground(Color.orange);
            retorno = false;
        } else {
            tfRg.setBackground(Color.WHITE);
        }
        
        if(tformatadoDataNasc.getText().equals("  /  /    ")) {
            tformatadoDataNasc.setBackground(Color.orange);
            retorno = false;
        } else {
            tformatadoDataNasc.setBackground(Color.WHITE);
        }
        
        if(tfRua.getText().equals("")) {
            tfRua.setBackground(Color.orange);
            retorno = false;
        } else {
            tfRua.setBackground(Color.WHITE);
        }
        
        if(tfNumeroEnd.getText().equals("")) {
            tfNumeroEnd.setBackground(Color.orange);
            retorno = false;
        } else {
            tfNumeroEnd.setBackground(Color.WHITE);
        }
        
        if(tfCidade.getText().equals("")) {
            tfCidade.setBackground(Color.orange);
            retorno = false;
        } else {
            tfCidade.setBackground(Color.WHITE);
        }
        
        return retorno;
    }
    
    public void preencherFormCom(Cliente cliente)
    {
        tfNome.setText(cliente.getNome());
        tfCodigo.setText(Integer.toString(cliente.getCodigo()));
        tformatadoCpf.setText(cliente.getCpf());
        tfRg.setText(cliente.getRg());
        tformatadoDataNasc.setText(DateCustomizer.DateToStr(cliente.getDataNascimento()));

        tfRua.setText(cliente.getRua());
        tfNumeroEnd.setText(cliente.getNumeroEnd());
        tfComplemento.setText(cliente.getComplemento());
        comboEstado.setSelectedItem((String)cliente.getEstado());
        tfCidade.setText(cliente.getCidade());
        tformatadoCep.setText(cliente.getCep());

        tformatadoTelCelular.setText(cliente.getFoneCelular());
        tformatadoTelComercial.setText(cliente.getFoneComercial());
        tformatadoTelResidencial.setText(cliente.getFoneResidencial());
        tfEmail.setText(cliente.getEmail());
        taObs.setText(cliente.getObservação());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscarCpf;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox comboEstado;
    private javax.swing.JScrollPane jScrollPaneObs;
    private javax.swing.JLabel lbCelular;
    private javax.swing.JLabel lbCep;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbDataNasc;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbErro;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbModeloData;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbObservacao;
    private javax.swing.JLabel lbRg;
    private javax.swing.JLabel lbRua;
    private javax.swing.JLabel lbTelComercial;
    private javax.swing.JLabel lbcomplemento;
    private javax.swing.JPanel painelContato;
    private javax.swing.JPanel painelDadosPessoais;
    private javax.swing.JPanel painelEndereco;
    private javax.swing.JTextArea taObs;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNumeroEnd;
    private javax.swing.JTextField tfRg;
    private javax.swing.JTextField tfRua;
    private javax.swing.JLabel tfTelResidencial;
    private javax.swing.JFormattedTextField tformatadoCep;
    private javax.swing.JFormattedTextField tformatadoCpf;
    private javax.swing.JFormattedTextField tformatadoDataNasc;
    private javax.swing.JFormattedTextField tformatadoTelCelular;
    private javax.swing.JFormattedTextField tformatadoTelComercial;
    private javax.swing.JFormattedTextField tformatadoTelResidencial;
    // End of variables declaration//GEN-END:variables
}
